import type { MetaRecord } from 'nextra';

const meta: MetaRecord = {
  '1': 'Two Sum',
  '3': 'Longest Substring Without Repeating Characters',
  '5': 'Longest Palindromic Substring',
  '8': 'String to Integer (atoi)',
  '11': 'Container With Most Water',
  '12': 'Integer to Roman',
  '16': 'Sum Closest',
  '18': 'Sum',
  '19': 'Remove Nth Node From End of List',
  '24': 'Swap Nodes in Pairs',
  '26': 'Remove Duplicates from Sorted Array',
  '29': 'Divide Two Integers',
  '31': 'Next Permutation',
  '33': 'Search in Rotated Sorted Array',
  '34': 'Find First and Last Position of Element in Sorted Array',
  '36': 'Valid Sudoku',
  '38': 'Count and Say',
  '39': 'Combination Sum',
  '40': 'Combination Sum II',
  '41': 'First Missing Positive',
  '42': 'Trapping Rain Water',
  '43': 'Multiply Strings',
  '48': 'Rotate Image',
  '50': 'Pow(x, n)',
  '51': 'N-Queens',
  '52': 'N-Queens II',
  '54': 'Spiral Matrix',
  '55': 'Jump Game',
  '56': 'Merge Intervals',
  '57': 'Insert Interval',
  '58': 'Length of Last Word',
  '59': 'Spiral Matrix II',
  '61': 'Rotate List',
  '62': 'Unique Paths',
  '64': 'Minimum Path Sum',
  '70': 'Climbing Stairs',
  '71': 'Simplify Path',
  '72': 'Edit Distance',
  '73': 'Set Matrix Zeroes',
  '74': 'Search a 2D Matrix',
  '75': 'Sort Colors',
  '76': 'Minimum Window Substring',
  '78': 'Subsets',
  '79': 'Word Search',
  '80': 'Remove Duplicates from Sorted Array II',
  '81': 'Search in Rotated Sorted Array II',
  '85': 'Maximal Rectangle',
  '86': 'Partition List',
  '88': 'Merge Sorted Array',
  '89': 'Gray Code',
  '90': 'Subsets II',
  '91': 'Decode Ways',
  '92': 'Reverse Linked List II',
  '93': 'Restore IP Addresses',
  '94': 'Binary Tree Inorder Traversal',
  '97': 'Interleaving String',
  '99': 'Recover Binary Search Tree',
  '100': 'Same Tree',
  '101': 'Symmetric Tree',
  '102': 'Binary Tree Level Order Traversal',
  '103': 'Binary Tree Zigzag Level Order Traversal',
  '105': 'Construct Binary Tree from Preorder and Inorder Traversal',
  '106': 'Construct Binary Tree from Inorder and Postorder Traversal',
  '107': 'Binary Tree Level Order Traversal II',
  '108': 'Convert Sorted Array to Binary Search Tree',
  '109': 'Convert Sorted List to Binary Search Tree',
  '110': 'Balanced Binary Tree',
  '111': 'Minimum Depth of Binary Tree',
  '112': 'Path Sum',
  '113': 'Path Sum II',
  '114': 'Flatten Binary Tree to Linked List',
  '118': "Pascal's Triangle",
  '119': "Pascal's Triangle II",
  '120': 'Triangle',
  '121': 'Best Time to Buy and Sell Stock',
  '122': 'Best Time to Buy and Sell Stock II',
  '123': 'Best Time to Buy and Sell Stock III',
  '124': 'Binary Tree Maximum Path Sum',
  '125': 'Valid Palindrome',
  '128': 'Longest Consecutive Sequence',
  '129': 'Sum Root to Leaf Numbers',
  '131': 'Palindrome Partitioning',
  '134': 'Gas Station',
  '135': 'Candy',
  '138': 'Copy List with Random Pointer',
  '139': 'Word Break',
  '140': 'Word Break II',
  '141': 'Linked List Cycle',
  '142': 'Linked List Cycle II',
  '143': 'Reorder List',
  '144': 'Binary Tree Preorder Traversal',
  '146': 'LRU Cache',
  '147': 'Insertion Sort List',
  '148': 'Sort List',
  '149': 'Max Points on a Line',
  '150': 'Evaluate Reverse Polish Notation',
  '151': 'Reverse Words in a String',
  '160': 'Intersection of Two Linked Lists',
  '164': 'Maximum Gap',
  '165': 'Compare Version Numbers',
  '166': 'Fraction to Recurring Decimal',
  '167': 'Two Sum II - Input Array Is Sorted',
  '168': 'Excel Sheet Column Title',
  '169': 'Majority Element',
  '171': 'Excel Sheet Column Number',
  '172': 'Factorial Trailing Zeroes',
  '173': 'Binary Search Tree Iterator',
  '179': 'Largest Number',
  '187': 'Repeated DNA Sequences',
  '188': 'Best Time to Buy and Sell Stock IV',
  '191': 'Number of 1 Bits',
  '198': 'House Robber',
  '199': 'Binary Tree Right Side View',
  '201': 'Bitwise AND of Numbers Range',
  '202': 'Happy Number',
  '204': 'Count Primes',
  '205': 'Isomorphic Strings',
  '207': 'Course Schedule',
  '208': 'Implement Trie (Prefix Tree)',
  '211': 'Design Add and Search Words Data Structure',
  '212': 'Word Search II',
  '214': 'Shortest Palindrome',
  '215': 'Kth Largest Element in an Array',
  '221': 'Maximal Square',
  '222': 'Count Complete Tree Nodes',
  '223': 'Rectangle Area',
  '224': 'Basic Calculator',
  '225': 'Implement Stack using Queues',
  '227': 'Basic Calculator II',
  '228': 'Summary Ranges',
  '229': 'Majority Element II',
  '230': 'Kth Smallest Element in a BST',
  '232': 'Implement Queue using Stacks',
  '234': 'Palindrome Linked List',
  '236': 'Lowest Common Ancestor of a Binary Tree',
  '238': 'Product of Array Except Self',
  '241': 'Different Ways to Add Parentheses',
  '242': 'Valid Anagram',
  '257': 'Binary Tree Paths',
  '258': 'Add Digits',
  '260': 'Single Number III',
  '263': 'Ugly Number',
  '264': 'Ugly Number II',
  '268': 'Missing Number',
  '273': 'Integer to English Words',
  '274': 'H-Index',
  '275': 'H-Index II',
  '279': 'Perfect Squares',
  '283': 'Move Zeroes',
  '287': 'Find the Duplicate Number',
  '289': 'Game of Life',
  '290': 'Word Pattern',
  '292': 'Nim Game',
  '295': 'Find Median from Data Stream',
  '299': 'Bulls and Cows',
  '300': 'Longest Increasing arrsequence',
  '303': 'Range Sum Query - Immutable',
  '304': 'Range Sum Query 2D - Immutable',
  '306': 'Additive Number',
  '307': 'Range Sum Query - Mutable',
  '310': 'Minimum Height Trees',
  '313': 'Super Ugly Number',
  '316': 'Remove Duplicate Letters',
  '326': 'Power of Three',
  '328': 'Odd Even Linked List',
  '330': 'Patching Array',
  '338': 'Counting Bits',
  '341': 'Flatten Nested List Iterator',
  '342': 'Power of Four',
  '343': 'Integer Break',
  '345': 'Reverse Vowels of a String',
  '347': 'Top K Frequent Elements',
  '349': 'Intersection of Two Arrays',
  '352': 'Data Stream as Disjoint Intervals',
  '367': 'Valid Perfect Square',
  '368': 'Largest Divisible Subset',
  '374': 'Guess Number Higher or Lower',
  '376': 'Wiggle Subsequence',
  '377': 'Combination Sum IV',
  '380': 'Insert Delete GetRandom O(1)',
  '386': 'Lexicographical Numbers',
  '389': 'Find the Difference',
  '392': 'Is Subsequence',
  '401': 'Binary Watch',
  '402': 'Remove K Digits',
  '404': 'Sum of Left Leaves',
  '405': 'Convert a Number to Hexadecimal',
  '406': 'Queue Reconstruction by Height',
  '407': 'Trapping Rain Water II',
  '409': 'Longest Palindrome',
  '412': 'Fizz Buzz',
  '414': 'Third Maximum Number',
  '415': 'Add Strings',
  '419': 'Battleships in a Board',
  '429': 'N-ary Tree Level Order Traversal',
  '432': 'All O`one Data Structure',
  '433': 'Minimum Genetic Mutation',
  '434': 'Number of Segments in a String',
  '435': 'Non-overlapping Intervals',
  '440': 'K-th Smallest in Lexicographical Order',
  '442': 'Find All Duplicates in an Array',
  '443': 'String Compression',
  '445': 'Add Two Numbers II',
  '448': 'Find All Numbers Disappeared in an Array',
  '451': 'Sort Characters By Frequency',
  '452': 'Minimum Number of Arrows to Burst Balloons',
  '455': 'Assign Cookies',
  '458': 'Poor Pigs',
  '459': 'Repeated Substring Pattern',
  '461': 'Hamming Distance',
  '462': 'Minimum Moves to Equal Array Elements II',
  '463': 'Island Perimeter',
  '472': 'Concatenated Words',
  '476': 'Number Complement',
  '482': 'License Key Formatting',
  '485': 'Max Consecutive Ones',
  '492': 'Construct the Rectangle',
  '495': 'Teemo Attacking',
  '496': 'Next Greater Element I',
  '500': 'Keyboard Row',
  '501': 'Find Mode in Binary Search Tree',
  '502': 'IPO',
  '504': 'Base 7',
  '506': 'Relative Ranks',
  '507': 'Perfect Number',
  '509': 'Fibonacci Number',
  '513': 'Find Bottom Left Tree Value',
  '514': 'Freedom Trail',
  '515': 'Find Largest Value in Each Tree Row',
  '520': 'Detect Capital',
  '521': 'Longest Uncommon Subsequence I',
  '523': 'Continuous Subarray Sum',
  '525': 'Contiguous Array',
  '530': 'Minimum Absolute Difference in BST',
  '537': 'Complex Number Multiplication',
  '539': 'Minimum Time Difference',
  '541': 'Reverse String II',
  '542': 'Matrix',
  '543': 'Diameter of Binary Tree',
  '552': 'Student Attendance Record II',
  '557': 'Sum of Even Numbers After Queries',
  '559': 'Maximum Depth of N-ary Tree',
  '561': 'Array Partition',
  '563': 'Binary Tree Tilt',
  '564': 'Find the Closest Palindrome',
  '567': 'Permutation in String',
  '572': 'Subtree of Another Tree',
  '575': 'Distribute Candies',
  '576': 'Out of Boundary Paths',
  '583': 'Delete Operation for Two Strings',
  '587': 'Erect the Fence',
  '589': 'N-ary Tree Preorder Traversal',
  '590': 'N-ary Tree Postorder Traversal',
  '592': 'Fraction Addition and Subtraction',
  '594': 'Longest Harmonious Subsequence',
  '598': 'Range Addition II',
  '599': 'Minimum Index Sum of Two Lists',
  '605': 'Can Place Flowers',
  '606': 'Construct String from Binary Tree',
  '621': 'Task Scheduler',
  '623': 'Add One Row to Tree',
  '624': 'Maximum Distance in Arrays',
  '628': 'Maximum Product of Three Numbers',
  '629': 'K Inverse Pairs Array',
  '630': 'Course Schedule III',
  '632': 'Smallest Range Covering Elements from K Lists',
  '633': 'Sum of Square Numbers',
  '637': 'Average of Levels in Binary Tree',
  '641': 'Design Circular Deque',
  '643': 'Maximum Average Subarray I',
  '647': 'Palindromic Substrings',
  '648': 'Replace Words',
  '649': 'Dota2 Senate',
  '654': 'Maximum Binary Tree',
  '657': 'Robot Return to Origin',
  '658': 'Find K Closest Elements',
  '661': 'Image Smoother',
  '664': 'Strange Printer',
  '665': 'Non-decreasing Array',
  '670': 'Maximum Swap',
  '671': 'Second Minimum Node In a Binary Tree',
  '673': 'Number of Longest Increasing Subsequence',
  '674': 'Longest Continuous Increasing Subsequence',
  '678': 'Valid Parenthesis String',
  '680': 'Valid Palindrome II',
  '682': 'Baseball Game',
  '684': 'Redundant Connection',
  '688': 'Knight Probability in Chessboard',
  '689': 'Maximum Sum of 3 Non-Overlapping Subarrays',
  '693': 'Binary Number with Alternating Bits',
  '697': 'Degree of an Array',
  '703': 'Kth Largest Element in a Stream',
  '706': 'Design HashMap',
  '713': 'Subarray Product Less Than K',
  '714': 'Best Time to Buy and Sell Stock with Transaction Fee',
  '717': '-bit and 2-bit Characters',
  '718': 'Maximum Length of Repeated Subarray',
  '719': 'Find K-th Smallest Pair Distance',
  '724': 'Find Pivot Index',
  '725': 'Split Linked List in Parts',
  '726': 'Number of Atoms',
  '728': 'Self Dividing Numbers',
  '729': 'My Calendar I',
  '731': 'My Calendar II',
  '735': 'Asteroid Collision',
  '739': 'Daily Temperatures',
  '745': 'Prefix and Suffix Search',
  '746': 'Min Cost Climbing Stairs',
  '747': 'Largest Number At Least Twice of Others',
  '748': 'Shortest Completing Word',
  '752': 'Open the Lock',
  '762': 'Prime Number of Set Bits in Binary Representation',
  '763': 'Partition Labels',
  '766': 'Toeplitz Matrix',
  '769': 'Max Chunks To Make Sorted',
  '771': 'Jewels and Stones',
  '773': 'Sliding Puzzle',
  '779': 'K-th Symbol in Grammar',
  '783': 'Minimum Distance Between BST Nodes',
  '785': 'Is Graph Bipartite?',
  '786': 'K-th Smallest Prime Fraction',
  '787': 'Cheapest Flights Within K Stops',
  '790': 'Domino and Tromino Tiling',
  '791': 'Custom Sort String',
  '796': 'Rotate String',
  '797': 'All Paths From Source to Target',
  '799': 'Champagne Tower',
  '802': 'Find Eventual Safe States',
  '806': 'Number of Lines To Write String',
  '807': 'Max Increase to Keep City Skyline',
  '811': 'Subdomain Visit Count',
  '814': 'Binary Tree Pruning',
  '815': 'Bus Routes',
  '819': 'Most Common Word',
  '820': 'Short Encoding of Words',
  '821': 'Shortest Distance to a Character',
  '823': 'Binary Trees With Factors',
  '824': 'Goat Latin',
  '826': 'Most Profit Assigning Work',
  '827': 'Making A Large Island',
  '830': 'Positions of Large Groups',
  '832': 'Flipping an Image',
  '834': 'Sum of Distances in Tree',
  '836': 'Rectangle Overlap',
  '837': 'New 21 Game',
  '838': 'Push Dominoes',
  '840': 'Magic Squares In Grid',
  '841': 'Keys and Rooms',
  '844': 'Backspace String Compare',
  '846': 'Hand of Straights',
  '847': 'Shortest Path Visiting All Nodes',
  '852': 'Peak Index in a Mountain Array',
  '857': 'Minimum Cost to Hire K Workers',
  '860': 'Lemonade Change',
  '861': 'Score After Flipping Matrix',
  '862': 'Shortest Subarray with Sum at Least K',
  '863': 'All Nodes Distance K in Binary Tree',
  '865': 'Smallest Subtree with all the Deepest Nodes',
  '867': 'Transpose Matrix',
  '868': 'Binary Gap',
  '872': 'Leaf-Similar Trees',
  '874': 'Walking Robot Simulation',
  '875': 'Koko Eating Bananas',
  '876': 'Middle of the Linked List',
  '880': 'Decoded String at Index',
  '881': 'Boats to Save People',
  '883': 'Projection Area of 3D Shapes',
  '884': 'Uncommon Words from Two Sentences',
  '885': 'Spiral Matrix III',
  '886': 'Possible Bipartition',
  '888': 'Fair Candy Swap',
  '889': 'Construct Binary Tree from Preorder and Postorder Traversal',
  '890': 'Find and Replace Pattern',
  '892': 'Surface Area of 3D Shapes',
  '893': 'Groups of Special-Equivalent Strings',
  '894': 'All Possible Full Binary Trees',
  '896': 'Monotonic Array',
  '899': 'Orderly Queue',
  '901': 'Online Stock Span',
  '905': 'Sort Array By Parity',
  '907': 'Sum of Subarray Minimums',
  '908': 'Smallest Range I',
  '914': 'X of a Kind in a Deck of Cards',
  '916': 'Word Subsets',
  '917': 'Reverse Only Letters',
  '921': 'Minimum Add to Make Parentheses Valid',
  '922': 'Sort Array By Parity II',
  '925': 'Long Pressed Name',
  '930': 'Binary Subarrays With Sum',
  '931': 'Minimum Falling Path Sum',
  '933': 'Number of Recent Calls',
  '934': 'Shortest Bridge',
  '935': 'Knight Dialer',
  '938': 'Range Sum of BST',
  '941': 'Valid Mountain Array',
  '942': 'DI String Match',
  '944': 'Delete Columns to Make Sorted',
  '945': 'Minimum Increment to Make Array Unique',
  '947': 'Most Stones Removed with Same Row or Column',
  '948': 'Bag of Tokens',
  '950': 'Reveal Cards In Increasing Order',
  '951': 'Flip Equivalent Binary Trees',
  '953': 'Verifying an Alien Dictionary',
  '959': 'Regions Cut By Slashes',
  '961': 'N-Repeated Element in Size 2N Array',
  '962': 'Maximum Width Ramp',
  '965': 'Univalued Binary Tree',
  '967': 'Numbers With Same Consecutive Differences',
  '968': 'Binary Tree Cameras',
  '969': 'Pancake Sorting',
  '974': 'Subarray Sums Divisible by K',
  '977': 'Squares of a Sorted Array',
  '979': 'Distribute Coins in Binary Tree',
  '980': 'Unique Paths III',
  '983': 'Minimum Cost For Tickets',
  '985': 'Sum of Even Numbers After Queries',
  '987': 'Vertical Order Traversal of a Binary Tree',
  '988': 'Smallest String Starting From Leaf',
  '989': 'Add to Array-Form of Integer',
  '992': 'Subarrays with K Different Integers',
  '993': 'Cousins in Binary Tree',
  '995': 'Minimum Number of K Consecutive Bit Flips',
  '997': 'Find the Town Judge',
  '999': 'Available Captures for Rook',
  '1002': 'Find Common Characters',
  '1004': 'Max Consecutive Ones III',
  '1005': 'Maximize Sum Of Array After K Negations',
  '1008': 'Construct Binary Search Tree from Preorder Traversal',
  '1013': 'Partition Array Into Three Parts With Equal Sum',
  '1014': 'Best Sightseeing Pair',
  '1018': 'Binary Prefix Divisible By 5',
  '1021': 'Remove Outermost Parentheses',
  '1022': 'Sum of Root To Leaf Binary Numbers',
  '1026': 'Maximum Difference Between Node and Ancestor',
  '1030': 'Matrix Cells in Distance Order',
  '1035': 'Uncrossed Lines',
  '1037': 'Valid Boomerang',
  '1038': 'Binary Search Tree to Greater Sum Tree',
  '1043': 'Partition Array for Maximum Sum',
  '1046': 'Last Stone Weight',
  '1047': 'Remove All Adjacent Duplicates In String',
  '1048': 'Longest String Chain',
  '1051': 'Height Checker',
  '1052': 'Grumpy Bookstore Owner',
  '1061': 'Lexicographically Smallest Equivalent String',
  '1072': 'Flip Columns For Maximum Number of Equal Rows',
  '1074': 'Number of Submatrices That Sum to Target',
  '1078': 'Occurrences After Bigram',
  '1079': 'Letter Tile Possibilities',
  '1089': 'Duplicate Zeros',
  '1095': 'Find in Mountain Array',
  '1103': 'Distribute Candies to People',
  '1104': 'Path In Zigzag Labelled Binary Tree',
  '1105': 'Filling Bookcase Shelves',
  '1106': 'Parsing A Boolean Expression',
  '1108': 'Defanging an IP Address',
  '1110': 'Delete Nodes And Return Forest',
  '1111': 'Maximum Nesting Depth of Two Valid Parentheses Strings',
  '1122': 'Relative Sort Array',
  '1123': 'Lowest Common Ancestor of Deepest Leaves',
  '1128': 'Number of Equivalent Domino Pairs',
  '1137': 'N-th Tribonacci Number',
  '1140': 'Stone Game II',
  '1143': 'Longest Common Subsequence',
  '1146': 'Snapshot Array',
  '1154': 'Day of the Year',
  '1155': 'Number of Dice Rolls With Target Sum',
  '1160': 'Find Words That Can Be Formed by Characters',
  '1161': 'Maximum Level Sum of a Binary Tree',
  '1171': 'Remove Zero Sum Consecutive Nodes from Linked List',
  '1175': 'Prime Arrangements',
  '1185': 'Day of the Week',
  '1187': 'Make Array Strictly Increasing',
  '1189': 'Maximum Number of Balloons',
  '1190': 'Reverse Substrings Between Each Pair of Parentheses',
  '1200': 'Minimum Absolute Difference',
  '1207': 'Unique Number of Occurrences',
  '1208': 'Get Equal Substrings Within Budget',
  '1217': 'Minimum Cost to Move Chips to The Same Position',
  '1218': 'Longest Arithmetic Subsequence of Given Difference',
  '1219': 'Path with Maximum Gold',
  '1220': 'Count Vowels Permutation',
  '1221': 'Split a String in Balanced Strings',
  '1222': 'Queens That Can Attack the King',
  '1232': 'Check If It Is a Straight Line',
  '1233': 'Remove Sub-Folders from the Filesystem',
  '1239': 'Maximum Length of a Concatenated String with Unique Characters',
  '1248': 'Count Number of Nice Subarrays',
  '1249': 'Minimum Remove to Make Valid Parentheses',
  '1252': 'Cells with Odd Values in a Matrix',
  '1255': 'Maximum Score Words Formed by Letters',
  '1261': 'Find Elements in a Contaminated Binary Tree',
  '1266': 'Minimum Time Visiting All Points',
  '1267': 'Count Servers that Communicate',
  '1268': 'Search Suggestions System',
  '1269': 'Number of Ways to Stay in the Same Place After Some Steps',
  '1275': 'Find Winner on a Tic Tac Toe Game',
  '1277': 'Count Square Submatrices with All Ones',
  '1281': 'Subtract the Product and Sum of Digits of an Integer',
  '1282': 'Group the People Given the Group Size They Belong To',
  '1286': 'Iterator for Combination',
  '1287': 'Element Appearing More Than 25% In Sorted Array',
  '1289': 'Minimum Falling Path Sum II',
  '1290': 'Convert Binary Number in a Linked List to Integer',
  '1291': 'Sequential Digits',
  '1293': 'Shortest Path in a Grid with Obstacles Elimination',
  '1295': 'Find Numbers with Even Number of Digits',
  '1299': 'Replace Elements with Greatest Element on Right Side',
  '1304': 'Find N Unique Integers Sum up to Zero',
  '1305': 'All Elements in Two Binary Search Trees',
  '1309': 'Decrypt String from Alphabet to Integer Mapping',
  '1310': 'XOR Queries of a Subarray',
  '1313': 'Decompress Run-Length Encoded List',
  '1315': 'Sum of Nodes with Even-Valued Grandparent',
  '1317': 'Convert Integer to the Sum of Two No-Zero Integers',
  '1323': 'Maximum 69 Number',
  '1325': 'Delete Leaves With a Given Value',
  '1328': 'Break a Palindrome',
  '1329': 'Sort the Matrix Diagonally',
  '1331': 'Rank Transform of an Array',
  '1332': 'Remove Palindromic Subsequences',
  '1334': 'Find the City With the Smallest Number of Neighbors at a Threshold Distance',
  '1335': 'Minimum Difficulty of a Job Schedule',
  '1337': 'The K Weakest Rows in a Matrix',
  '1339': 'Maximum Product of Splitted Binary Tree',
  '1346': 'Check If N and Its Double Exist',
  '1347': 'Minimum Number of Steps to Make Two Strings Anagram',
  '1351': 'Count Negative Numbers in a Sorted Matrix',
  '1354': 'Construct Target Array With Multiple Sums',
  '1356': 'Sort Integers by The Number of 1 Bits',
  '1359': 'Count All Valid Pickup and Delivery Options',
  '1360': 'Number of Days Between Two Dates',
  '1361': 'Validate Binary Tree Nodes',
  '1365': 'How Many Numbers Are Smaller Than the Current Number',
  '1367': 'Linked List in Binary Tree',
  '1368': 'Minimum Cost to Make at Least One Valid Path in a Grid',
  '1370': 'Increasing Decreasing String',
  '1371': 'Find the Longest Substring Containing Vowels in Even Counts',
  '1380': 'Lucky Numbers in a Matrix',
  '1381': 'Design a Stack With Increment Operation',
  '1382': 'Balance a Binary Search Tree',
  '1385': 'Find the Distance Value Between Two Arrays',
  '1389': 'Create Target Array in the Given Order',
  '1394': 'Find Lucky Integer in an Array',
  '1395': 'Count Number of Teams',
  '1399': 'Count Largest Group',
  '1400': 'Construct K Palindrome Strings',
  '1403': 'Minimum Subsequence in Non-Increasing Order',
  '1404': 'Number of Steps to Reduce a Number in Binary Representation to One',
  '1405': 'Longest Happy String',
  '1408': 'String Matching in an Array',
  '1413': 'Minimum Value to Get Positive Step by Step Sum',
  '1415': 'The k-th Lexicographical String of All Happy Strings of Length n',
  '1417': 'Reformat The String',
  '1418': 'Display Table of Food Orders in a Restaurant',
  '1420': 'Build Array Where You Can Find The Maximum Exactly K Comparisons',
  '1422': 'Maximum Score After Splitting a String',
  '1423': 'Maximum Points You Can Obtain from Cards',
  '1424': 'Diagonal Traverse II',
  '1425': 'Constrained Subsequence Sum',
  '1431': 'Kids With the Greatest Number of Candies',
  '1436': 'Destination City',
  '1437': "Check If All 1's Are at Least Length K Places Away",
  '1438': 'Longest Continuous Subarray With Absolute Diff Less Than or Equal to Limit',
  '1441': 'Build an Array With Stack Operations',
  '1442': 'Count Triplets That Can Form Two Arrays of Equal XOR',
  '1443': 'Minimum Time to Collect All Apples in a Tree',
  '1446': 'Consecutive Characters',
  '1448': 'Count Good Nodes in Binary Tree',
  '1450': 'Number of Students Doing Homework at a Given Time',
  '1455': 'Check If a Word Occurs As a Prefix of Any Word in a Sentence',
  '1456': 'Maximum Number of Vowels in a Substring of Given Length',
  '1457': 'Pseudo-Palindromic Paths in a Binary Tree',
  '1458': 'Max Dot Product of Two Subsequences',
  '1460': 'Make Two Arrays Equal by Reversing Subarrays',
  '1461': 'Check If a String Contains All Binary Codes of Size K',
  '1462': 'Course Schedule IV',
  '1463': 'Cherry Pickup II',
  '1464': 'Maximum Product of Two Elements in an Array',
  '1465': 'Maximum Area of a Piece of Cake After Horizontal and Vertical Cuts',
  '1470': 'Shuffle the Array',
  '1472': 'Design Browser History',
  '1475': 'Final Prices With a Special Discount in a Shop',
  '1476': 'Subrectangle Queries',
  '1480': 'Running Sum of 1d Array',
  '1481': 'Least Number of Unique Integers after K Removals',
  '1482': 'Minimum Number of Days to Make m Bouquets',
  '1486': 'XOR Operation in an Array',
  '1491': 'Average Salary Excluding the Minimum and Maximum Salary',
  '1492': 'The kth Factor of n',
  '1493': "Longest Subarray of 1's After Deleting One Element",
  '1496': 'Path Crossing',
  '1497': 'Check If Array Pairs Are Divisible by k',
  '1502': 'Can Make Arithmetic Progression From Sequence',
  '1503': 'Last Moment Before All Ants Fall Out of a Plank',
  '1507': 'Reformat Date',
  '1508': 'Range Sum of Sorted Subarray Sums',
  '1509': 'Minimum Difference Between Largest and Smallest Value in Three Moves',
  '1512': 'Number of Good Pairs',
  '1514': 'Path with Maximum Probability',
  '1518': 'Water Bottles',
  '1519': 'Number of Nodes in the Sub-Tree With the Same Label',
  '1523': 'Count Odd Numbers in an Interval Range',
  '1528': 'Shuffle String',
  '1529': 'Minimum Suffix Flips',
  '1530': 'Number of Good Leaf Nodes Pairs',
  '1531': 'String Compression II',
  '1534': 'Count Good Triplets',
  '1539': 'Kth Missing Positive Number',
  '1544': 'Make The String Great',
  '1545': 'Find Kth Bit in Nth Binary String',
  '1547': 'Minimum Cost to Cut a Stick',
  '1550': 'Three Consecutive Odds',
  '1552': 'Magnetic Force Between Two Balls',
  '1556': 'Thousand Separator',
  '1557': 'Minimum Number of Vertices to Reach All Nodes',
  '1560': 'Most Visited Sector in  a Circular Track',
  '1561': 'Maximum Number of Coins You Can Get',
  '1566': 'Detect Pattern of Length M Repeated K or More Times',
  '1568': 'Minimum Number of Days to Disconnect Island',
  '1569': 'Number of Ways to Reorder Array to Get Same BST',
  '1572': 'Matrix Diagonal Sum',
  '1574': 'Shortest Subarray to be Removed to Make Array Sorted',
  '1576': "Replace All ?'s to Avoid Consecutive Repeating Characters",
  '1578': 'Minimum Time to Make Rope Colorful',
  '1579': 'Remove Max Number of Edges to Keep Graph Fully Traversable',
  '1582': 'Special Positions in a Binary Matrix',
  '1588': 'Sum of All Odd Length Subarrays',
  '1590': 'Make Sum Divisible by P',
  '1592': 'Rearrange Spaces Between Words',
  '1593': 'Split a String Into the Max Number of Unique Substrings',
  '1598': 'Crawler Log Folder',
  '1603': 'Design Parking System',
  '1605': 'Find Valid Matrix Given Row and Column Sums',
  '1608': 'Special Array With X Elements Greater Than or Equal X',
  '1609': 'Even Odd Tree',
  '1611': 'Minimum One Bit Operations to Make Integers Zero',
  '1614': 'Maximum Nesting Depth of the Parentheses',
  '1619': 'Mean of Array After Removing Some Elements',
  '1624': 'Largest Substring Between Two Equal Characters',
  '1629': 'Slowest Key',
  '1630': 'Arithmetic Subarrays',
  '1636': 'Sort Array by Increasing Frequency',
  '1637': 'Widest Vertical Area Between Two Points Containing No Points',
  '1638': 'Count Substrings That Differ by One Character',
  '1639': 'Number of Ways to Form a Target String Given a Dictionary',
  '1640': 'Check Array Formation Through Concatenation',
  '1642': 'Furthest Building You Can Reach',
  '1646': 'Get Maximum in Generated Array',
  '1647': 'Minimum Deletions to Make Character Frequencies Unique',
  '1652': 'Defuse the Bomb',
  '1653': 'Minimum Deletions to Make String Balanced',
  '1656': 'Design an Ordered Stream',
  '1657': 'Determine if Two Strings Are Close',
  '1658': 'Minimum Operations to Reduce X to Zero',
  '1662': 'Check If Two String Arrays are Equivalent',
  '1668': 'Maximum Repeating Substring',
  '1669': 'Merge In Between Linked Lists',
  '1671': 'Minimum Number of Removals to Make Mountain Array',
  '1672': 'Richest Customer Wealth',
  '1678': 'Goal Parser Interpretation',
  '1679': 'Max Number of K-Sum Pairs',
  '1680': 'Concatenation of Consecutive Binary Numbers',
  '1684': 'Count the Number of Consistent Strings',
  '1685': 'Sum of Absolute Differences in a Sorted Array',
  '1688': 'Count of Matches in Tournament',
  '1689': 'Partitioning Into Minimum Number Of Deci-Binary Numbers',
  '1694': 'Reformat Phone Number',
  '1695': 'Maximum Erasure Value',
  '1696': 'Jump Game VI',
  '1700': 'Number of Students Unable to Eat Lunch',
  '1701': 'Average Waiting Time',
  '1704': 'Determine if String Halves Are Alike',
  '1706': 'Where Will the Ball Fall',
  '1710': 'Maximum Units on a Truck',
  '1716': 'Calculate Money in Leetcode Bank',
  '1717': 'Maximum Score From Removing Substrings',
  '1720': 'Decode XORed Array',
  '1721': 'Swapping Nodes in a Linked List',
  '1725': 'Number Of Rectangles That Can Form The Largest Square',
  '1726': 'Tuple with Same Product',
  '1727': 'Largest Submatrix With Rearrangements',
  '1732': 'Find the Highest Altitude',
  '1736': 'Latest Time by Replacing Hidden Digits',
  '1742': 'Maximum Number of Balls in a Box',
  '1743': 'Restore the Array From Adjacent Pairs',
  '1748': 'Sum of Unique Elements',
  '1750': 'Minimum Length of String After Deleting Similar Ends',
  '1751': 'Maximum Number of Events That Can Be Attended II',
  '1752': 'Check if Array Is Sorted and Rotated',
  '1758': 'Minimum Changes To Make Alternating Binary String',
  '1759': 'Count Number of Homogenous Substrings',
  '1760': 'Minimum Limit of Balls in a Bag',
  '1763': 'Longest Nice Substring',
  '1765': 'Map of Highest Peak',
  '1769': 'Minimum Number of Operations to Move All Balls to Each Box',
  '1773': 'Count Items Matching a Rule',
  '1779': 'Find Nearest Point That Has the Same X or Y Coordinate',
  '1784': 'Check if Binary String Has at Most One Segment of Ones',
  '1790': 'Check if One String Swap Can Make Strings Equal',
  '1791': 'Find Center of Star Graph',
  '1792': 'Maximum Average Pass Ratio',
  '1793': 'Maximum Score of a Good Subarray',
  '1796': 'Second Largest Digit in a String',
  '1799': 'Maximize Score After N Operations',
  '1800': 'Maximum Ascending Subarray Sum',
  '1805': 'Number of Different Integers in a String',
  '1806': 'Minimum Number of Operations to Reinitialize a Permutation',
  '1812': 'Determine Color of a Chessboard Square',
  '1813': 'Sentence Similarity III',
  '1814': 'Count Nice Pairs in an Array',
  '1816': 'Truncate Sentence',
  '1817': 'Finding the Users Active Minutes',
  '1822': 'Sign of the Product of an Array',
  '1823': 'Find the Winner of the Circular Game',
  '1827': 'Minimum Operations to Make the Array Increasing',
  '1828': 'Queries on Number of Points Inside a Circle',
  '1829': 'Maximum XOR for Each Query',
  '1832': 'Check if the Sentence Is Pangram',
  '1833': 'Maximum Ice Cream Bars',
  '1834': 'Single-Threaded CPU',
  '1837': 'Sum of Digits in Base K',
  '1838': 'Frequency of the Most Frequent Element',
  '1844': 'Replace All Digits with Characters',
  '1845': 'Seat Reservation Manager',
  '1846': 'Maximum Element After Decreasing and Rearranging',
  '1848': 'Minimum Distance to the Target Element',
  '1854': 'Maximum Population Year',
  '1859': 'Sorting the Sentence',
  '1861': 'Rotating the Box',
  '1863': 'Sum of All Subset XOR Totals',
  '1869': 'Longer Contiguous Segments of Ones than Zeros',
  '1870': 'Minimum Speed to Arrive on Time',
  '1876': 'Substrings of Size Three with Distinct Characters',
  '1877': 'Minimize Maximum Pair Sum in Array',
  '1880': 'Check if Word Equals Summation of Two Words',
  '1886': 'Determine Whether Matrix Can Be Obtained By Rotation',
  '1887': 'Reduction Operations to Make the Array Elements Equal',
  '1893': 'Check if All the Integers in a Range Are Covered',
  '1894': 'Find the Student that Will Replace the Chalk',
  '1897': 'Redistribute Characters to Make All Strings Equal',
  '1903': 'Largest Odd Number in String',
  '1905': 'Count Sub Islands',
  '1909': 'Remove One Element to Make the Array Strictly Increasing',
  '1910': 'Remove All Occurrences of a Substring',
  '1913': 'Maximum Product Difference Between Two Pairs',
  '1915': 'Number of Wonderful Substrings',
  '1920': 'Build Array from Permutation',
  '1921': 'Eliminate Maximum Number of Monsters',
  '1925': 'Count Square Sum Triples',
  '1926': 'Nearest Exit from Entrance in Maze',
  '1929': 'Concatenation of Array',
  '1930': 'Unique Length-3 Palindromic Subsequences',
  '1935': 'Maximum Number of Words You Can Type',
  '1937': 'Maximum Number of Points with Cost',
  '1941': 'Check if All Characters Have Equal Number of Occurrences',
  '1942': 'The Number of the Smallest Unoccupied Chair',
  '1945': 'Sum of Digits of String After Convert',
  '1952': 'Three Divisors',
  '1957': 'Delete Characters to Make Fancy String',
  '1961': 'Check If String Is a Prefix of Array',
  '1962': 'Remove Stones to Minimize the Total',
  '1963': 'Minimum Number of Swaps to Make the String Balanced',
  '1964': 'Find the Longest Valid Obstacle Course at Each Position',
  '1967': 'Number of Strings That Appear as Substrings in Word',
  '1971': 'Find if Path Exists in Graph',
  '1974': 'Minimum Time to Type Word Using Special Typewriter',
  '1975': 'Maximum Matrix Sum',
  '1979': 'Find Greatest Common Divisor of Array',
  '1980': 'Find Unique Binary String',
  '1984': 'Minimum Difference Between Highest and Lowest of K Scores',
  '1991': 'Find the Middle Index in Array',
  '1992': 'Find All Groups of Farmland',
  '1995': 'Count Special Quadruplets',
  '1996': 'The Number of Weak Characters in the Game',
  '2000': 'Reverse Prefix of Word',
  '2006': 'Count Number of Pairs With Absolute Difference K',
  '2009': 'Minimum Number of Operations to Make Array Continuous',
  '2011': 'Final Value of Variable After Performing Operations',
  '2016': 'Maximum Difference Between Increasing Elements',
  '2017': 'Grid Game',
  '2022': 'Convert 1D Array Into 2D Array',
  '2023': 'Number of Pairs of Strings With Concatenation Equal to Target',
  '2024': 'Maximize the Confusion of an Exam',
  '2027': 'Minimum Moves to Convert String',
  '2028': 'Find Missing Observations',
  '2032': 'Two Out of Three',
  '2037': 'Minimum Number of Moves to Seat Everyone',
  '2042': 'Check if Numbers Are Ascending in a Sentence',
  '2044': 'Count Number of Maximum Bitwise-OR Subsets',
  '2045': 'Second Minimum Time to Reach Destination',
  '2047': 'Number of Valid Words in a Sentence',
  '2050': 'Parallel Courses III',
  '2053': 'Kth Distinct String in an Array',
  '2054': 'Two Best Non-Overlapping Events',
  '2057': 'Smallest Index With Equal Value',
  '2058': 'Find the Minimum and Maximum Number of Nodes Between Critical Points',
  '2062': 'Count Vowel Substrings of a String',
  '2064': 'Minimized Maximum of Products Distributed to Any Store',
  '2068': 'Check Whether Two Strings are Almost Equivalent',
  '2070': 'Most Beautiful Item for Each Query',
  '2073': 'Time Needed to Buy Tickets',
  '2078': 'Two Furthest Houses With Different Colors',
  '2079': 'Watering Plants',
  '2085': 'Count Common Words With One Occurrence',
  '2089': 'Find Target Indices After Sorting Array',
  '2090': 'K Radius Subarray Averages',
  '2092': 'Find All People With Secret',
  '2094': 'Finding 3-Digit Even Numbers',
  '2096': 'Step-By-Step Directions From a Binary Tree Node to Another',
  '2097': 'Valid Arrangement of Pairs',
  '2099': 'Find Subsequence of Length K With the Largest Sum',
  '2101': 'Detonate the Maximum Bombs',
  '2103': 'Rings and Rods',
  '2108': 'Find First Palindromic String in the Array',
  '2109': 'Adding Spaces to a String',
  '2114': 'Maximum Number of Words Found in Sentences',
  '2116': 'Check if a Parentheses String Can Be Valid',
  '2119': 'A Number After a Double Reversal',
  '2120': 'Execution of All Suffix Instructions Staying in a Grid',
  '2124': "Check if All A's Appears Before All B's",
  '2125': 'Number of Laser Beams in a Bank',
  '2127': 'Maximum Employees to Be Invited to a Meeting',
  '2129': 'Capitalize the Title',
  '2130': 'Maximum Twin Sum of a Linked List',
  '2131': 'Longest Palindrome by Concatenating Two Letter Words',
  '2133': 'Check if Every Row and Column Contains All Numbers',
  '2134': "Minimum Swaps to Group All 1's Together II",
  '2136': 'Earliest Possible Day of Full Bloom',
  '2138': 'Divide a String Into Groups of Size k',
  '2140': 'Solving Questions With Brainpower',
  '2141': 'Maximum Running Time of N Computers',
  '2144': 'Minimum Cost of Buying Candies With Discount',
  '2147': 'Number of Ways to Divide a Long Corridor',
  '2148': 'Count Elements With Strictly Smaller and Greater Elements',
  '2149': 'Rearrange Array Elements by Sign',
  '2154': 'Keep Multiplying Found Values by Two',
  '2160': 'Minimum Sum of Four Digit Number After Splitting Digits',
  '2161': 'Partition Array According to Given Pivot',
  '2164': 'Sort Even and Odd Indices Independently',
  '2169': 'Count Operations to Obtain Zero',
  '2176': 'Count Equal and Divisible Pairs in an Array',
  '2180': 'Count Integers With Even Digit Sum',
  '2181': 'Merge Nodes in Between Zeros',
  '2182': 'Construct String With Repeat Limit',
  '2185': 'Counting Words With a Given Prefix',
  '2186': 'Minimum Number of Steps to Make Two Strings Anagram II',
  '2187': 'Minimum Time to Complete Trips',
  '2190': 'Most Frequent Number Following Key In an Array',
  '2191': 'Sort the Jumbled Numbers',
  '2192': 'All Ancestors of a Node in a Directed Acyclic Graph',
  '2194': 'Cells in a Range on an Excel Sheet',
  '2196': 'Create Binary Tree From Descriptions',
  '2200': 'Find All K-Distant Indices in an Array',
  '2206': 'Divide Array Into Equal Pairs',
  '2210': 'Count Hills and Valleys in an Array',
  '2215': 'Find the Difference of Two Arrays',
  '2220': 'Minimum Bit Flips to Convert Number',
  '2221': 'Find Triangular Sum of an Array',
  '2224': 'Minimum Number of Operations to Convert Time',
  '2225': 'Find Players With Zero or One Losses',
  '2235': 'Add Two Integers',
  '2236': 'Root Equals Sum of Children',
  '2239': 'Find Closest Number to Zero',
  '2243': 'Calculate Digit Sum of a String',
  '2244': 'Minimum Rounds to Complete All Tasks',
  '2246': 'Longest Path With Different Adjacent Characters',
  '2248': 'Intersection of Multiple Arrays',
  '2251': 'Number of Flowers in Full Bloom',
  '2255': 'Count Prefixes of a Given String',
  '2256': 'Minimum Average Difference',
  '2257': 'Count Unguarded Cells in the Grid',
  '2259': 'Remove Digit From Number to Maximize Result',
  '2264': 'Largest 3-Same-Digit Number in String',
  '2265': 'Count Nodes Equal to Average of Subtree',
  '2269': 'Find the K-Beauty of a Number',
  '2270': 'Number of Ways to Split Array',
  '2273': 'Find Resultant Array After Removing Anagrams',
  '2275': 'Largest Combination With Bitwise AND Greater Than Zero',
  '2278': 'Percentage of Letter in String',
  '2279': 'Maximum Bags With Full Capacity of Rocks',
  '2283': 'Check if Number Has Equal Digit Count and Digit Value',
  '2285': 'Maximum Total Importance of Roads',
  '2287': 'Rearrange Characters to Make Target String',
  '2290': 'Minimum Obstacle Removal to Reach Corner',
  '2293': 'Min Max Game',
  '2294': 'Partition Array Such That Maximum Difference Is K',
  '2299': 'Strong Password Checker II',
  '2303': 'Calculate Amount Paid in Taxes',
  '2309': 'Greatest English Letter in Upper and Lower Case',
  '2315': 'Count Asterisks',
  '2317': 'Maximum XOR After Operations',
  '2319': 'Check if Matrix Is X-Matrix',
  '2325': 'Decode the Message',
  '2326': 'Spiral Matrix IV',
  '2331': 'Evaluate Boolean Binary Tree',
  '2335': 'Minimum Amount of Time to Fill Cups',
  '2336': 'Smallest Number in Infinite Set',
  '2337': 'Move Pieces to Obtain a String',
  '2341': 'Maximum Number of Pairs in Array',
  '2347': 'Best Poker Hand',
  '2349': 'Design a Number Container System',
  '2351': 'First Letter to Appear Twice',
  '2352': 'Equal Row and Column Pairs',
  '2357': 'Make Array Zero by Subtracting Equal Amounts',
  '2363': 'Merge Similar Items',
  '2364': 'Count Number of Bad Pairs',
  '2366': 'Minimum Replacements to Sort the Array',
  '2367': 'Number of Arithmetic Triplets',
  '2370': 'Longest Ideal Subsequence',
  '2373': 'Largest Local Values in a Matrix',
  '2375': 'Construct Smallest Number From DI String',
  '2379': 'Minimum Recolors to Get K Consecutive Black Blocks',
  '2381': 'Shifting Letters II',
  '2383': 'Minimum Hours of Training to Win a Competition',
  '2385': 'Amount of Time for Binary Tree to Be Infected',
  '2389': 'Longest Subsequence With Limited Sum',
  '2390': 'Removing Stars From a String',
  '2391': 'Minimum Amount of Time to Collect Garbage',
  '2392': 'Build a Matrix With Conditions',
  '2395': 'Find Subarrays With Equal Sum',
  '2399': 'Check Distances Between Same Letters',
  '2402': 'Meeting Rooms III',
  '2405': 'Optimal Partition of String',
  '2406': 'Divide Intervals Into Minimum Number of Groups',
  '2409': 'Count Days Spent Together',
  '2413': 'Smallest Even Multiple',
  '2415': 'Reverse Odd Levels of Binary Tree',
  '2416': 'Sum of Prefix Scores of Strings',
  '2418': 'Sort the People',
  '2419': 'Longest Subarray With Maximum Bitwise AND',
  '2423': 'Remove Letter To Equalize Frequency',
  '2425': 'Bitwise XOR of All Pairings',
  '2427': 'Number of Common Factors',
  '2428': 'Maximum Sum of an Hourglass',
  '2429': 'Minimize XOR',
  '2432': 'The Employee That Worked on the Longest Task',
  '2433': 'Find The Original Array of Prefix Xor',
  '2437': 'Number of Valid Clock Times',
  '2441': 'Largest Positive Integer That Exists With Its Negative',
  '2442': 'Count Number of Distinct Integers After Reverse Operations',
  '2444': 'Count Subarrays With Fixed Bounds',
  '2446': 'Determine if Two Events Have Conflict',
  '2451': 'Odd String Difference',
  '2455': 'Average Value of Even Numbers That Are Divisible by Three',
  '2458': 'Height of Binary Tree After Subtree Removal Queries',
  '2460': 'Apply Operations to an Array',
  '2461': 'Maximum Sum of Distinct Subarrays With Length K',
  '2462': 'Total Cost to Hire K Workers',
  '2463': 'Minimum Total Distance Traveled',
  '2465': 'Number of Distinct Averages',
  '2466': 'Count Ways To Build Good Strings',
  '2469': 'Convert the Temperature',
  '2471': 'Minimum Number of Operations to Sort a Binary Tree by Level',
  '2475': 'Number of Unequal Triplets in Array',
  '2481': 'Minimum Cuts to Divide a Circle',
  '2482': 'Difference Between Ones and Zeros in Row and Column',
  '2483': 'Minimum Penalty for a Shop',
  '2485': 'Find the Pivot Integer',
  '2486': 'Append Characters to String to Make Subsequence',
  '2487': 'Remove Nodes From Linked List',
  '2490': 'Circular Sentence',
  '2491': 'Divide Players Into Teams of Equal Skill',
  '2493': 'Divide Nodes Into the Maximum Number of Groups',
  '2496': 'Maximum Value of a String in an Array',
  '2500': 'Delete Greatest Value in Each Row',
  '2501': 'Longest Square Streak in an Array',
  '2506': 'Count Pairs Of Similar Strings',
  '2511': 'Maximum Enemy Forts That Can Be Captured',
  '2515': 'Shortest Distance to Target String in a Circular Array',
  '2516': 'Take K of Each Character From Left and Right',
  '2520': 'Count the Digits That Divide a Number',
  '2525': 'Categorize Box According to Criteria',
  '2529': 'Maximum Count of Positive Integer and Negative Integer',
  '2530': 'Maximal Score After Applying K Operations',
  '2535': 'Difference Between Element Sum and Digit Sum of an Array',
  '2540': 'Minimum Common Value',
  '2542': 'Maximum Subsequence Score',
  '2544': 'Alternating Digit Sum',
  '2545': 'Sort the Students by Their Kth Score',
  '2549': 'Count Distinct Numbers on Board',
  '2553': 'Separate the Digits in an Array',
  '2554': 'Maximum Number of Integers to Choose From a Range I',
  '2558': 'Take Gifts From the Richest Pile',
  '2559': 'Count Vowel Strings in Ranges',
  '2562': 'Find the Array Concatenation Value',
  '2563': 'Count the Number of Fair Pairs',
  '2566': 'Maximum Difference by Remapping a Digit',
  '2570': 'Merge Two 2D Arrays by Summing Values',
  '2574': 'Left and Right Sum Differences',
  '2577': 'Minimum Time to Visit a Cell In a Grid',
  '2578': 'Split With Minimum Sum',
  '2582': 'Pass the Pillow',
  '2583': 'Kth Largest Sum in a Binary Tree',
  '2586': 'Count the Number of Vowel Strings in Range',
  '2591': 'Distribute Money to Maximum Children',
  '2593': 'Find Score of an Array After Marking All Elements',
  '2595': 'Number of Even and Odd Bits',
  '2597': 'The Number of Beautiful Subsets',
  '2600': 'K Items With the Maximum Sum',
  '2601': 'Prime Subtraction Operation',
  '2605': 'Form Smallest Number From Two Digit Arrays',
  '2609': 'Find the Longest Balanced Substring of a Binary String',
  '2610': 'Convert an Array Into a 2D Array With Conditions',
  '2614': 'Prime In Diagonal',
  '2618': 'Check if Object Instance of Class',
  '2619': 'Array Prototype Last',
  '2621': 'Sleep',
  '2622': 'Cache With Time Limit',
  '2623': 'Memoize',
  '2624': 'Snail Traversal',
  '2625': 'Flatten Deeply Nested Array',
  '2626': 'Array Reduce Transformation',
  '2627': 'Debounce',
  '2628': 'JSON Deep Equal',
  '2629': 'Function Composition',
  '2631': 'Group By',
  '2632': 'Curry',
  '2633': 'Convert Object to JSON String',
  '2634': 'Filter Elements from Array',
  '2635': 'Apply Transform Over Each Element in Array',
  '2636': 'Promise Pool',
  '2637': 'Promise Time Limit',
  '2639': 'Find the Width of Columns of a Grid',
  '2640': 'Find the Score of All Prefixes of an Array',
  '2641': 'Cousins in Binary Tree II',
  '2642': 'Design Graph With Shortest Path Calculator',
  '2643': 'Row With Maximum Ones',
  '2644': 'Find the Maximum Divisibility Score',
  '2648': 'Generate Fibonacci Sequence',
  '2649': 'Nested Array Generator',
  '2651': 'Calculate Delayed Arrival Time',
  '2652': 'Sum Multiples',
  '2656': 'Maximum Sum With Exactly K Elements',
  '2657': 'Find the Prefix Common Array of Two Arrays',
  '2658': 'Maximum Number of Fish in a Grid',
  '2660': 'Determine the Winner of a Bowling Game',
  '2661': 'First Completely Painted Row or Column',
  '2666': 'Allow One Function Call',
  '2670': 'Find the Distinct Difference Array',
  '2675': 'Array of Objects to Matrix',
  '2676': 'Throttle',
  '2677': 'Chunk Array',
  '2678': 'Number of Senior Citizens',
  '2682': 'Find the Losers of the Circular Game',
  '2683': 'Neighboring Bitwise XOR',
  '2684': 'Maximum Number of Moves in a Grid',
  '2693': 'Call Function with Custom Context',
  '2694': 'Event Emitter',
  '2695': 'Array Wrapper',
  '2696': 'Minimum String Length After Removing Substrings',
  '2697': 'Lexicographically Smallest Palindrome',
  '2700': 'Differences Between Two Objects',
  '2706': 'Buy Two Chocolates',
  '2707': 'Extra Characters in a String',
  '2709': 'Greatest Common Divisor Traversal',
  '2710': 'Remove Trailing Zeros From a String',
  '2716': 'Minimize String Length',
  '2717': 'Semi-Ordered Permutation',
  '2721': 'Execute Asynchronous Functions in Parallel',
  '2722': 'Join Two Arrays by ID',
  '2723': 'Add Two Promises',
  '2724': 'Sort By',
  '2725': 'Interval Cancellation',
  '2726': 'Calculator with Method Chaining',
  '2727': 'Is Object Empty',
  '2729': 'Check if The Number is Fascinating',
  '2733': 'Neither Minimum nor Maximum',
  '2739': 'Total Distance Traveled',
  '2742': 'Painting the Walls',
  '2744': 'Find Maximum Number of String Pairs',
  '2748': 'Number of Beautiful Pairs',
  '2751': 'Robot Collisions',
  '2760': 'Longest Even Odd Subarray With Threshold',
  '2762': 'Continuous Subarrays',
  '2765': 'Longest Alternating Subarray',
  '2769': 'Find the Maximum Achievable Number',
  '2778': 'Sum of Squares of Special Elements',
  '2779': 'Maximum Beauty of an Array After Applying Operation',
  '2784': 'Check if Array is Good',
  '2785': 'Sort Vowels in a String',
  '2788': 'Split Strings by Separator',
  '2798': 'Number of Employees Who Met the Target',
  '2806': 'Account Balance After Rounded Purchase',
  '2807': 'Insert Greatest Common Divisors in Linked List',
  '2810': 'Faulty Keyboard',
  '2812': 'Find the Safest Path in a Grid',
  '2815': 'Max Pair Sum in an Array',
  '2816': 'Double a Number Represented as a Linked List',
  '2824': 'Count Pairs Whose Sum is Less than Target',
  '2825': 'Make String a Subsequence Using Cyclic Increments',
  '2828': 'Check if a String Is an Acronym of Words',
  '2833': 'Furthest Point From Origin',
  '2839': 'Check if Strings Can be Made Equal With Operations I',
  '2843': 'Count Symmetric Integers',
  '2848': 'Points That Intersect With Cars',
  '2849': 'Determine if a Cell Is Reachable at a Given Time',
  '2855': 'Minimum Right Shifts to Sort the Array',
  '2859': 'Sum of Values at Indices With K Set Bits',
  '2864': 'Maximum Odd Binary Number',
  '2869': 'Minimum Operations to Collect Elements',
  '2870': 'Minimum Number of Operations to Make Array Empty',
  '2872': 'Maximum Number of K-Divisible Components',
  '2873': 'Maximum Value of an Ordered Triplet I',
  '2894': 'Divisible and Non-divisible Sums Difference',
  '2899': 'Last Visited Integers',
  '2900': 'Longest Unequal Adjacent Groups Subsequence I',
  '2903': 'Find Indices With Index and Value Difference I',
  '2908': 'Minimum Sum of Mountain Triplets I',
  '2913': 'Subarrays Distinct Element Sum of Squares I',
  '2914': 'Minimum Number of Changes to Make Binary String Beautiful',
  '2917': 'Find the K-or of an Array',
  '2923': 'Find Champion I',
  '2924': 'Find Champion II',
  '2928': 'Distribute Candies Among Children I',
  '2932': 'Maximum Strong Pair XOR I',
  '2937': 'Make Three Strings Equal',
  '2938': 'Separate Black and White Balls',
  '2940': 'Find Building Where Alice and Bob Can Meet',
  '2942': 'Find Words Containing Character',
  '2946': 'Matrix Similarity After Cyclic Shifts',
  '2948': 'Make Lexicographically Smallest Array by Swapping Elements',
  '2951': 'Find the Peaks',
  '2956': 'Find Common Elements Between Two Arrays',
  '2958': 'Length of Longest Subarray With at Most K Frequency',
  '2960': 'Count Tested Devices After Test Operations',
  '2962': 'Count Subarrays Where Max Element Appears at Least K Times',
  '2965': 'Find Missing and Repeated Values',
  '2966': 'Divide Array Into Arrays With Max Difference',
  '2970': 'Count the Number of Incremovable Subarrays I',
  '2971': 'Find Polygon With the Largest Perimeter',
  '2974': 'Minimum Number Game',
  '2976': 'Minimum Cost to Convert String I',
  '2980': 'Check if Bitwise OR Has Trailing Zeros',
  '2981': 'Find Longest Special Substring That Occurs Thrice I',
  '2996': 'Smallest Missing Integer Greater Than Sequential Prefix Sum',
  '2997': 'Minimum Number of Operations to Make Array XOR Equal to K',
  '3000': 'Maximum Area of Longest Diagonal Rectangle',
  '3005': 'Count Elements With Maximum Frequency',
  '3010': 'Divide an Array Into Subarrays With Minimum Cost I',
  '3011': 'Find if Array Can Be Sorted',
  '3014': 'Minimum Number of Pushes to Type Word I',
  '3016': 'Minimum Number of Pushes to Type Word II',
  '3019': 'Number of Changing Keys',
  '3024': 'Type of Triangle',
  '3028': 'Ant on the Boundary',
  '3033': 'Modify the Matrix',
  '3038': 'Maximum Number of Operations With the Same Score I',
  '3042': 'Count Prefix and Suffix Pairs I',
  '3043': 'Find the Length of the Longest Common Prefix',
  '3045': 'Count Prefix and Suffix Pairs II',
  '3046': 'Split the Array',
  '3065': 'Minimum Operations to Exceed Threshold Value I',
  '3068': 'Find the Maximum Sum of Node Values',
  '3069': 'Distribute Elements Into Two Arrays I',
  '3074': 'Apple Redistribution into Boxes',
  '3075': 'Maximize Happiness of Selected Children',
  '3079': 'Find the Sum of Encrypted Integers',
  '3083': 'Existence of a Substring in a String and Its Reverse',
  '3090': 'Maximum Length Substring With Two Occurrences',
  '3095': 'Shortest Subarray With OR at Least K I',
  '3097': 'Shortest Subarray With OR at Least K II',
  '3099': 'Harshad Number',
  '3105': 'Longest Strictly Increasing or Strictly Decreasing Subarray',
  '3110': 'Score of a String',
  '3114': 'Latest Time You Can Obtain After Replacing Characters',
  '3120': 'Count the Number of Special Characters I',
  '3127': 'Make a Square with the Same Color',
  '3131': 'Find the Integer Added to Array I',
  '3136': 'Valid Word',
  '3142': 'Check if Grid Satisfies Conditions',
  '3146': 'Permutation Difference between Two Strings',
  '3151': 'Special Array I',
  '3152': 'Special Array II',
  '3158': 'Find the XOR of Numbers Which Appear Twice',
  '3159': 'Find Occurrences of an Element in an Array',
  '3160': 'Find the Number of Distinct Colors Among the Balls',
  '3162': 'Find the Number of Good Pairs I',
  '3163': 'String Compression III',
  '3168': 'Minimum Number of Chairs in a Waiting Room',
  '3174': 'Clear Digits',
  '3178': 'Find the Child Who Has the Ball After K Seconds',
  '3184': 'Count Pairs That Form a Complete Day I',
  '3190': 'Find Minimum Operations to Make All Elements Divisible by Three',
  '3194': 'Minimum Average of Smallest and Largest Elements',
  '3195': 'Find the Minimum Area to Cover All Ones I',
  '3200': 'Maximum Height of a Triangle',
  '3203': 'Find Minimum Diameter After Merging Two Trees',
  '3206': 'Alternating Groups I',
  '3210': 'Find the Encrypted String',
  '3211': 'Generate Binary Strings Without Adjacent Zeros',
  '3216': 'Lexicographically Smallest String After a Swap',
  '3217': 'Delete Nodes From Linked List Present in Array',
  '3222': 'Find the Winning Player in Coin Game',
  '3223': 'Minimum Length of String After Operations',
  '3226': 'Number of Bit Changes to Make Two Integers Equal',
  '3232': 'Find if Digit Game Can Be Won',
  '3238': 'Find the Number of Winning Players',
  '3239': 'Minimum Number of Flips to Make Binary Grid Palindromic I',
  '3242': 'Design Neighbor Sum Service',
  '3243': 'Shortest Distance After Road Addition Queries I',
  '3248': 'Snake in Matrix',
  '3254': 'Find the Power of K-Size Subarrays I',
  '3258': 'Count Substrings That Satisfy K-Constraint I',
  '3264': 'Final Array State After K Multiplication Operations I',
  '3270': 'Find the Key of the Numbers',
  '3271': 'Hash Divided String',
  '3274': 'Check if Two Chessboard Squares Have the Same Color',
  '3280': 'Convert Date to Binary',
  '3285': 'Find Indices of Stable Mountains',
  '3289': 'The Two Sneaky Numbers of Digitville',
  '3300': 'Minimum Element After Replacement With Digit Sum',
  '3304': 'Find the K-th Character in String Game I',
  '3314': 'Construct the Minimum Bitwise Array I',
  '3318': 'Find X-Sum of All K-Long Subarrays I',
  '3324': 'Find the Sequence of Strings Appeared on the Screen',
  '3330': 'Find the Original Typed String I',
  '3340': 'Check Balanced String',
  '3345': 'Smallest Divisible Digit Product I',
  '3349': 'Adjacent Increasing Subarrays Detection I',
  '3354': 'Make Array Elements Equal to Zero',
  '3360': 'Stone Removal Game',
  '3364': 'Minimum Positive Sum Subarray',
  '3370': 'Smallest Number With All Set Bits',
  '3375': 'Minimum Operations to Make Array Values Equal to K',
  '3379': 'Transformed Array',
  '3386': 'Button with Longest Push Time',
  '3392': 'Count Subarrays of Length Three With a Condition',
  '3396': 'Minimum Number of Operations to Make Elements in Array Distinct',
  '3402': 'Minimum Operations to Make Columns Strictly Increasing',
  '3407': 'Substring Matching Pattern',
  '3417': 'Zigzag Grid Traversal With Skip',
  '3423': 'Maximum Difference Between Adjacent Elements in a Circular Array',
  '3427': 'Sum of Variable Length Subarrays',
  '3432': 'Count Partitions with Even Sum Difference',
  '3438': 'Find Valid Pair of Adjacent Digits in String',
  '3442': 'Maximum Difference Between Even and Odd Frequency I',
};

export default meta;
