packages:
  - packages/*
  - tooling/*
  - solution
  - website

catalog:
  eslint: ^9.20.1
  prettier: ^3.5.0
  typescript: ^5.7.3
  '@types/node': ^22.13.2

catalogs:
  jest:
    jest: ^29.7.0
    ts-jest: ^29.2.5
    '@types/jest': ^29.5.14

onlyBuiltDependencies:
  - esbuild
  - sharp
